# Generated by Django 6.0.5 on 2026-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('Order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50)),
                ('RestaurantName', models.CharField(max_length=50)),
                ('FoodItem', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('DeliveryAddress', models.CharField(max_length=200)),
                ('OrderStatus', models.CharField(max_length=30)),
            ],
        ),
    ]
